### ISSUE TITLE
Remove UI elements related to "Login as Customer" from Admin Panel grids

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2-login-as-customer#15]
As a merchant I want to remove links to Login as Customer from admin grids so only essential columns and actions are shown, and each grid requires less screen resolution to display all default columns of data.

**Business Value**
The admin grid should be free of unnecessary or infrequently-used columns to enable performant loading and help admin users quickly find relevant information.

**Assumptions and Notes**
 * No changes in this story for button actions (such as 'Login as Customer' header button action on Customer Detail page in admin)

**AC**
* **UX design:** [UX_LoginAsCustomer_March_12_3_2020.pdf](https://github.com/magento/magento2-login-as-customer/files/4325537/UX_LoginAsCustomer_March_12_3_2020.pdf)
 * 'Login' column removed from Customers Grid in admin
 * 'Action II' column removed from Orders Grid in admin

**Demo Steps**
 1. Open admin panel
 1. Open Customers grid
 1. Verify 'Login' column is not displayed
 1. Verify 'Login' column cannot be added to grid
 1. Open Orders grid
 1. Verify 'Action II' column is not displayed
 1. Verify 'Action II' column cannot be added to grid

**Comment by ihorvansach** [comment]
Working on it

**Comment by naydav** [comment]
https://github.com/magento/magento2-login-as-customer/pull/23

**Comment by engcom-Delta** [comment]
Issue is fixed by https://github.com/magento/magento2-login-as-customer/pull/23 and it is not reproducible with last commit [9204ab7](https://github.com/magento/magento2-login-as-customer/commit/9204ab78f6f69cd1f8a0bf496a58fb36b3486eb5)

![image](https://user-images.githubusercontent.com/51681379/79843028-5ae3e400-83c2-11ea-9d88-c52ef55b196a.png)
![image](https://user-images.githubusercontent.com/51681379/79843114-77801c00-83c2-11ea-992d-fec7956b010a.png)
